import type { Metadata } from "next";
import { Monoton, Audiowide } from "next/font/google";
import "./globals.css";
import NavBar from "../src/components/navbar/index";

const titlesFont = Monoton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-titles",
  display: "swap",
});

const bodyFont = Audiowide({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-body",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${titlesFont.variable} ${bodyFont.variable}`}>
        <NavBar />
        <main>{children}</main>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
