import type { Metadata } from "next";
import { Monoton, Audiowide  } from "next/font/google";
import "./globals.css";
import NavBar from "../src/components/navbar/index";

const titlesFont = Monoton({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-titles",
});

const bodyFont = Audiowide ({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${titlesFont.variable} ${bodyFont.variable}`}>
        <NavBar />
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
