import { Metadata } from "next";
import { Orbitron, Monoton } from "next/font/google";
import "../globals.css";
import Navbar from "../components/navbar";
import { dir } from "i18next";
import { languages } from "../i18n/settings";
import { LanguageProvider } from "../context/lng";
import Footer from "../components/footer";
import AudioPlayer from "../components/audioPlayer";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

const titlesFont = Monoton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-titles",
  display: "swap",
});

const bodyFont = Orbitron({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-body",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    lng: string;
  };
}

export default function RootLayout({
  children,
  params: { lng },
}: RootLayoutProps) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={`${titlesFont.variable} ${bodyFont.variable}`}>
        <LanguageProvider language={lng}>
          <Navbar />
          <main style={{ display: "grid", flex: 1, gridTemplateColumns: "30% 70%", alignItems: "center", padding: "0 1rem" }}>
            <AudioPlayer />
            {children}
          </main>
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
